"""change tokens table and make actions table

Revision ID: 02c8ff673d0d
Revises: 8022f3697ba1
Create Date: 2022-02-07 08:37:57.831434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c8ff673d0d'
down_revision = '8022f3697ba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('manipulations')
    op.add_column('tokens', sa.Column('action_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tokens', 'actions', ['action_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.drop_column('tokens', 'action_id')
    op.create_table('manipulations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('manipulation', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], name='manipulations_token_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='manipulations_pkey')
    )
    op.drop_table('actions')
    # ### end Alembic commands ###
